### ISSUE TITLE
fatal error: core/vector.h: No such file or directory

### ISSUE THREAD

**Issue by YusufKhan-gamedev** [czapek1337/toy-kernel#1]
I have all the dependencies that you have specified(including limine) and when I run make kernel I get the error
```
[  3%] Building CXX object CMakeFiles/kernel.dir/src/acpi/acpi.cpp.o
/home/yusufkhan/toy/toy-kernel/kernel/src/acpi/acpi.cpp:1:10: fatal error: core/vector.h: No such file or directory
    1 | #include <core/vector.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [CMakeFiles/kernel.dir/build.make:76: CMakeFiles/kernel.dir/src/acpi/acpi.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:83: CMakeFiles/kernel.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:90: CMakeFiles/kernel.dir/rule] Error 2
make: *** [Makefile:124: kernel] Error 2

```
How do I fix this?

**Comment by czapek1337** [comment]
i'm not sure why that happens, i just tried building it using these commands and it worked just fine:
- `git clone https://github.com/czapek1337/toy-kernel`
- `cd toy-kernel`
- `git submodule update --init`
- `mkdir build`
- `CC=clang-12 CXX=clang++-12 cmake ..`
- `make all`

if you aren't doing so, you could try building it using clang, like i did, im not sure whats up with that, sorry about that

**Comment by YusufKhan-gamedev** [comment]
This fixes it, but there were a couple typos here, this is correct(replace clang-x and clang++-x with your clang version):

```
    git clone https://github.com/czapek1337/toy-kernel
    cd toy-kernel
    git submodule update --init
    mkdir build
    cd build
    CC=clang-x CXX=clang++-x cmake ..
    make all

```
