### ISSUE TITLE
How to configure new drivers

### ISSUE THREAD

**Issue by YusufKhan-gamedev** [czapek1337/toy-kernel#3]
Ive created a basic keyboard driver in /src/dev and was wondering how I would configure it with the rest of the kernel to allow for it(with debugging and so on).

**Comment by czapek1337** [comment]
honestly im unsure about this as i havent thought that this project would get this far lol, you can just place if somewhere there, like you said, for example in src/dev, or maybe make it src/driver? it can be improved later down the line

**Comment by YusufKhan-gamedev** [comment]
Ill probably just create a lib/modules to put it in the fs and /drivers for putting it in code.
