### ISSUE TITLE
What is uint64_t in the context of Threads and Processes? 

### ISSUE THREAD

**Issue by YusufKhan-gamedev** [czapek1337/toy-kernel#4]
Im porting the Plan9 core utils to the toy kernel and many utils really need the exec syscall to function.o When looking at process.cpp and process.h I see Process::spawn and Thread::spawn have a 64 bit int call entry as one of its inputs. Could that section be skipped(when calling a application), and what does it do?

Is it just the variable thats passed?

**Comment by czapek1337** [comment]
there isnt really a libc there yet, exec is a very posix like syscall and i dont think i will be supporting it. regarding the "64 bit int call entry" its the place where the process/thread starts its execution, which is necessary obviously, for processes you can create one from an elf pointer, which contains the executable's entry point address which i use to create the main thread

**Comment by YusufKhan-gamedev** [comment]
Ill be creating a kernel module to put it in then.

**Comment by YusufKhan-gamedev** [comment]
regarding a libc, newlib looks quite easy to port if a couple things are added.
