### ISSUE TITLE
Minor issue: replace c++ with clang++ for arch users

### ISSUE THREAD

**Issue by YusufKhan-gamedev** [czapek1337/toy-kernel#6]
I tried to compile the Toy kernel on my laptop that runs arch and I keep getting the error
```
c++: error: unrecognized command-line option ‘-target’
make[2]: *** [libs/core/CMakeFiles/core.dir/build.make:76: libs/core/CMakeFiles/core.dir/src/core/lock.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:452: libs/core/CMakeFiles/core.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
 
```
When patching c++ with clang another error pops up, im too lazy to fix this issue if you want to you can fix this, its a bit of a minor issue due to a work around.

**Comment by czapek1337** [comment]
yeah that's something that i could totally fix, but i don't really support building with anything else than clang so that's expected - whenever i get around coding again i'll take care of it

**Comment by czapek1337** [comment]
starting with 970b3535b6468b15f51f61ce800d0b7a271dd1eb you will be able to compile the kernel with both llvm and gnu toolchains, i feel like we can close this now
