### ISSUE TITLE
(Reopened)How is "#include <system/syscalls.h>" valid syntax????

### ISSUE THREAD

**Issue by YusufKhan-gamedev** [czapek1337/toy-kernel#7]
Im just as confused as VS Codium, how is `#include <system/syscalls.h>` valid syntax while `#include <system/elf.h>` is not? Ive looked through all of the Cmake lists and I dont see anything that would make this make sense. 

Please help!

**Comment by czapek1337** [comment]
it doesn't work because there is no such file as elf.h in the system library

**Comment by YusufKhan-gamedev** [comment]
Oh I just realized how stupid I am, I thought it was in syscalls.h was in kernel/src/

**Comment by YusufKhan-gamedev** [comment]
With this in mind, should I commit libc stuff to /lib/sys?

**Comment by YusufKhan-gamedev** [comment]
Also, I find the BSD libc the fastest to port, should I enable BSD specific features, also should I enable legacy POSIX features(probably not I guess but still im asking)

**Comment by czapek1337** [comment]
posix compatibility wasn't even in plans but i can reconsider this since it would greatly increase software compatibility
