### ISSUE TITLE
Porting to ARM, RISCV, MIPS, PowerPC

### ISSUE THREAD

**Issue by YusufKhan-gamedev** [czapek1337/toy-kernel#8]
How would I begin porting the Toy kernel to other architectures?  Im creating a distribution of the Toy kernel for embedded systems and its a little hard for users to only use x86 embedded systems for it.

**Comment by czapek1337** [comment]
its a hard question, first thing that would have to be done is factoring all x86 specific things like cpu initialization, paging and interrupt handling/interrupt controller driver to a separate "sub-project" in the kernel, then we would need a common interface for virtual memory and handling interrupt, scheduler and syscall interface also need to be worked out of the base kernel to allow for other architectures, overall this is a big task and i dont think its one i will take upon until the kernel is somewhat functional

**Comment by YusufKhan-gamedev** [comment]
Would i386 be easily ported?

**Comment by czapek1337** [comment]
Well theoretically a 32 bit port shouldn't be too hard but as I already said I'd like to focus on getting a somewhat functional kernel first before branching out to different architectures
